// Code generated by "stringer -type CompilerMode"; DO NOT EDIT.

package lexarch

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Thompson-1]
	_ = x[Glushkov-2]
}

const _CompilerMode_name = "ThompsonGlushkov"

var _CompilerMode_index = [...]uint8{0, 8, 16}

func (i CompilerMode) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_CompilerMode_index)-1 {
		return "CompilerMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CompilerMode_name[_CompilerMode_index[idx]:_CompilerMode_index[idx+1]]
}
